---
title: "Lauren Price, M.P.P., R.T.S.B.A."
subtitle: "Houston, TX | 772-485-2635 | lauren.3.price@gmail.com | [LinkedIn](https://www.linkedin.com/in/lauren-price-data/) | [GitHub](https://github.com/pricele2) | [Calendly](https://calendly.com/lauren-3-price/quick-chat)"
format: PrettyPDF-pdf
date: today
date-format: long
---

\today

Dr. April Crawford and Dr. Tricia Zucker \newline
Professors and Co-Directors  \newline
Children's Learning Institute at UTHealth Houston \newline
Houston, Texas 

Dear Dr. Crawford and Dr. Zucker:

I am pleased to apply for the position of of Senior Program Manager with the Grants and Contracts team at the Children's Learning Institute. I am deeply passionate about the transformative power of early childhood programming: this specific role would let me contribute my grants and contracts domain knowledge, my technical/analytics skills, and leadership to an organization supporting our littlest learners. 

The strongest candidate for this position will bring their unique combination of four things: experience, skills, passions/values, and personality. My professional experience and technical skills are laid out in more detail in my attached full CV.

Briefly, after six years post-BA working in Colorado's nonprofit sector, I went back to school full time to earn my Master’s of Public Policy in K-12 Education and Leadership. I excelled in the quant-heavy program, regularly choosing doctoral-level courses to strengthen my methodology chops. Since graduating, I have spent over a decade in K-12 public education administration: grants, contracts, analytics, data governance, and regulatory compliance. I proudly served the students, teachers, and families of my community by doing thoughtful, clever work in the central office. With Houston ISD, for seven years I oversaw all aspects of three federal grants — budget and financial planning, accounting reconciliations, monitoring and measuring program outcomes, and preparing progress reports and grant proposals to government agencies. I oversaw $62.3M across 7 years with on-time semi-annual reporting to our funding agencies, a successful desk audit, and a Deloitte single audit with 0 findings.

Later on, I provided direction and guidance to senior District leadership about policies, new laws, and emerging issues around government funding and state/local privacy regulations. I led cross-functional District teams in negotiating with external entities over the appropriate and permissible use of student data, and I led the overhaul of the District's formal legal contracts for all entities using District data. I built stakeholder buy-in and rolled out new internal controls designed explicitly so that *it is easier for people to follow the correct process than to circumvent it*.

As for the *people* side of this leadership role, I am an experienced leader with seven years of managing, coaching, and mentoring both technical analysts and program staff. As a supervisor, I set high expectations and clear parameters, establish collaborative practices and team norms, and then both oversee and coach up where needed. I deliberately foster a high-performing, mutually accountable team culture — aiming to be the kind of leader that educational theorist Dr. Gloria Ladson-Billings might call a *warm demander*. But I also kindle a sense of together-ness, continuous improvement, and humor within my teams. 

For example, every September 30 I made a point to celebrate "Federal New Year's Eve!" with my administration team (3), accountants (3), and my grant program staff (6-9). We broke out the holiday decor, laughed about the small gifts I snuck onto their desks, and we met our deadlines together even under the stress of year-end time constraints.  

Thank you for your consideration, and I hope to hear from your team soon.

\vspace{12pt} 
Regards, 

Lauren Price

